server:
  port : 8383
  shutdown : graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    url: jdbc:h2:mem:lib-db;DATABASE_TO_UPPER=false
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect